global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules_compat.yml

scrape_configs:
  - job_name: "hass"
    scrape_interval: 60s
    metrics_path: /api/prometheus
    authorization:
      credentials_file: /run/secrets/hass-bearer-token
    scheme: https
    static_configs:
      - targets: ["hass.ext.tnt.photo:443"]
  - job_name: "immich_api"
    static_configs:
      - targets: ["immich-server:8081"]
  - job_name: "immich_microservices"
    static_configs:
      - targets: ["immich-server:8082"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: "watchtower"
    metrics_path: /v1/metrics
    bearer_token: demotoken
    static_configs:
      - targets: ["watchtower:8080"]
